// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bhati_jatha_count_report.Data;

#nullable disable

namespace bhati_jatha_count_report.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251027050420_AddSewaType")]
    partial class AddSewaType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("bhati_jatha_count_report.Models.Entities.Center", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CenterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CenterType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Centers");
                });

            modelBuilder.Entity("bhati_jatha_count_report.Models.Entities.SewaType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SewaName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SewaTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
