// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bhati_jatha_count_report.Data;

#nullable disable

namespace bhati_jatha_count_report.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251027063717_RecreateSewaNominalRoll")]
    partial class RecreateSewaNominalRoll
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("bhati_jatha_count_report.Models.Entities.Center", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CenterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CenterType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Centers");
                });

            modelBuilder.Entity("bhati_jatha_count_report.Models.Entities.SewaNominalRoll", b =>
                {
                    b.Property<string>("NominalRollToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SewaDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CentreName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Females")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InchargeContact")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InchargeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("JourneyDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Males")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SewaDuration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SewaName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SewaStartTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SewaType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalSewadars")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NominalRollToken", "SewaDate");

                    b.HasIndex("RowId")
                        .IsUnique();

                    b.ToTable("SewaNominalRolls");
                });

            modelBuilder.Entity("bhati_jatha_count_report.Models.Entities.SewaType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SewaName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SewaTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
