// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using bhati_jatha_count_report.Data;

#nullable disable

namespace bhati_jatha_count_report.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251031142114_AddManualSewadarCountToDailyActualCount")]
    partial class AddManualSewadarCountToDailyActualCount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("bhati_jatha_count_report.Models.Entities.AllotedCount", b =>
                {
                    b.Property<int>("WeekDay")
                        .HasColumnType("integer");

                    b.Property<int>("CenterId")
                        .HasColumnType("integer");

                    b.Property<int>("SewaTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.HasKey("WeekDay", "CenterId", "SewaTypeId");

                    b.HasIndex("CenterId");

                    b.HasIndex("SewaTypeId");

                    b.ToTable("AllotedCounts");
                });

            modelBuilder.Entity("bhati_jatha_count_report.Models.Entities.Center", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CenterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CenterType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Centers");
                });

            modelBuilder.Entity("bhati_jatha_count_report.Models.Entities.DailyActualCount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CenterId")
                        .HasColumnType("integer");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ManualSewadarCount")
                        .HasColumnType("integer");

                    b.Property<string>("NominalRollToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SewaTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CenterId");

                    b.HasIndex("SewaTypeId");

                    b.ToTable("DailyActualCounts");
                });

            modelBuilder.Entity("bhati_jatha_count_report.Models.Entities.SewaNominalRoll", b =>
                {
                    b.Property<string>("NominalRollToken")
                        .HasColumnType("text");

                    b.Property<DateTime>("SewaDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CentreName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Females")
                        .HasColumnType("integer");

                    b.Property<string>("InchargeContact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InchargeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("JourneyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Males")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SewaDuration")
                        .HasColumnType("integer");

                    b.Property<string>("SewaName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SewaStartTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SewaType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalSewadars")
                        .HasColumnType("integer");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NominalRollToken", "SewaDate");

                    b.ToTable("SewaNominalRolls");
                });

            modelBuilder.Entity("bhati_jatha_count_report.Models.Entities.SewaType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("SewaName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SewaTypes");
                });

            modelBuilder.Entity("bhati_jatha_count_report.Models.Entities.AllotedCount", b =>
                {
                    b.HasOne("bhati_jatha_count_report.Models.Entities.Center", "Center")
                        .WithMany()
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("bhati_jatha_count_report.Models.Entities.SewaType", "SewaType")
                        .WithMany()
                        .HasForeignKey("SewaTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Center");

                    b.Navigation("SewaType");
                });

            modelBuilder.Entity("bhati_jatha_count_report.Models.Entities.DailyActualCount", b =>
                {
                    b.HasOne("bhati_jatha_count_report.Models.Entities.Center", "Center")
                        .WithMany()
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("bhati_jatha_count_report.Models.Entities.SewaType", "SewaType")
                        .WithMany()
                        .HasForeignKey("SewaTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Center");

                    b.Navigation("SewaType");
                });
#pragma warning restore 612, 618
        }
    }
}
