-- If "Id" is a SERIAL or IDENTITY column and you want to insert explicit Ids,
-- temporarily allow it by setting the proper sequence afterward if required.

-- Insert statements for all centers
INSERT INTO "Centers" ("Id", "CenterName", "CenterType") VALUES
  (1, 'AMBEDKAR NAGAR', 'C'),
  (2, 'ASHOK NAGAR', 'C'),
  (3, 'ASHOK VIHAR', 'C'),
  (4, 'BIJWASAN', 'C'),
  (5, 'CHITRAKOOT', 'C'),
  (6, 'DARYAGANJ', 'C'),
  (7, 'DILSHAD GARDEN', 'C'),
  (8, 'DWARKA', 'C'),
  (9, 'GEETA COLONY', 'C'),
  (10, 'JAITPUR', 'C'),
  (11, 'JANAKPURI', 'C'),
  (12, 'KARALA', 'C'),
  (13, 'KARKARDOOMA', 'C'),
  (14, 'LAJPAT NAGAR', 'C'),
  (15, 'LODHI COLONY', 'C'),
  (16, 'MAYUR VIHAR', 'C'),
  (17, 'MAYUR VIHAR PH-1 EXT.', 'C'),
  (18, 'MOHAN GARDEN', 'C'),
  (19, 'MUNDKA', 'SC'),
  (20, 'NAJAFGARH', 'C'),
  (21, 'NANGLOI', 'C'),
  (22, 'NARELA', 'C'),
  (23, 'PASCHIM VIHAR', 'C'),
  (24, 'PITAMPURA', 'C'),
  (25, 'POONTH KHURD', 'C'),
  (26, 'PRIYADARSHNI VIHAR', 'C'),
  (27, 'QADIPUR', 'C'),
  (28, 'R.K. PURAM', 'C'),
  (29, 'RADIO COLONY', 'C'),
  (30, 'RANAJI ENCLAVE', 'C'),
  (31, 'RANI BAGH', 'C'),
  (32, 'SONIA VIHAR', 'C'),
  (33, 'SULTANPURI', 'C'),
  (34, 'UTTAM NAGAR', 'C'),
  (35, 'VASANT KUNJ', 'C'),
  (36, 'VIKASPURI', 'C'),
  (37, 'ROHINI', 'C');;


SELECT setval(pg_get_serial_sequence('"Centers"', 'Id'), (SELECT MAX("Id") FROM "Centers"));
